https://www.cs.princeton.edu/courses/archive/spring09/cos226/assignments/8puzzle.html



In [9]:
from puzzle import Board, dijkstra, path, SOLVED, UNSOLVABLE
import numpy as np
import sys

In [10]:
# 3 moves deep
test3 = Board(state=np.array([[1,2,3,4],[5,6,0,8],[9,10,7,12],[13,14,11,15]],dtype=np.int8))
print(test3.board)
chart3, heap3 = dijkstra(board=test3)
print(len(chart3), sys.getsizeof(chart3), sys.getsizeof(chart3) // len(chart3))
print(len(heap3), sys.getsizeof(heap3), sys.getsizeof(heap3) // len(heap3))

[[ 1  2  3  4]
 [ 5  6  0  8]
 [ 9 10  7 12]
 [13 14 11 15]]
SOLVED
sampled 20 states in 0.00 seconds
20 640 32
12 184 15


In [11]:
# 10 moves deep
test10 = Board(state=np.array([[2,3,7,4],[1,5,10,8],[9,6,0,12],[13,14,11,15]],dtype=np.int8))
print(test10.board)
chart10, heap10 = dijkstra(board=test10)
print(len(chart10), sys.getsizeof(chart10), sys.getsizeof(chart10) // len(chart10))
print(len(heap10), sys.getsizeof(heap10), sys.getsizeof(heap10) // len(heap10))

[[ 2  3  7  4]
 [ 1  5 10  8]
 [ 9  6  0 12]
 [13 14 11 15]]
SOLVED
sampled 3165 states in 0.03 seconds
3165 147552 46
1625 14360 8


In [13]:
# 15 moves deep
test15 = Board(state=np.array([[2,9,3,4],[1,6,7,8],[10,5,11,0],[13,14,15,12]],dtype=np.int8))
print(test15.board)
chart15, heap15 = dijkstra(board=test15)
print(len(chart15), sys.getsizeof(chart15), sys.getsizeof(chart15) // len(chart15))
print(len(heap15), sys.getsizeof(heap15), sys.getsizeof(heap15) // len(heap15))


[[ 2  9  3  4]
 [ 1  6  7  8]
 [10  5 11  0]
 [13 14 15 12]]
SOLVED
sampled 97314 states in 0.62 seconds
97314 5242968 53
48247 394968 8


In [16]:
# 20 moves deep
test20 = Board(state=np.array([[1,0,3,6],[9,2,7,4],[11,5,12,8],[13,10,14,15]],dtype=np.int8))
print(test20.board)
chart20, heap20 = dijkstra(board=test20)
print(len(chart20), sys.getsizeof(chart20), sys.getsizeof(chart20) // len(chart20))
print(len(heap20), sys.getsizeof(heap20), sys.getsizeof(heap20) // len(heap20))

[[ 1  0  3  6]
 [ 9  2  7  4]
 [11  5 12  8]
 [13 10 14 15]]
SOLVED
sampled 2128066 states in 14.37 seconds
2128066 83886168 39
1024748 8448728 8


In [14]:
# idk but it's valid 
test = Board(state=np.array([[12,9,3,0],[10,2,14,1],[7,6,4,15],[5,13,11,8]],dtype=np.int8))
print(test.board)
chart, heap = dijkstra(board=test)
print(len(chart), sys.getsizeof(chart), sys.getsizeof(chart) // len(chart))
print(len(heap), sys.getsizeof(heap), sys.getsizeof(heap) // len(heap))

[[12  9  3  0]
 [10  2 14  1]
 [ 7  6  4 15]
 [ 5 13 11  8]]
BIG HEAP, len(heap)=10000001
sampled 21392999 states in 203.22 seconds
21392999 671088736 31
10000001 89095160 8


In [ ]:
# from https://www.geeksforgeeks.org/check-instance-15-puzzle-solvable/
# A utility function to count inversions in given
# array . Note that this function can be
# optimized to work in O(n Log n) time. The idea
# here is to keep code small and simple.
N=4
def getInvCount(arr: list[int]):
    arr1=[]
    for y in arr:
        for x in y:
            arr1.append(x)
    arr=arr1
    inv_count = 0
    for i in range(N * N - 1):
        for j in range(i + 1,N * N):
            # count pairs(arr[i], arr[j]) such that 
            # i < j and arr[i] > arr[j]
            if (arr[j] and arr[i] and arr[i] > arr[j]):
                inv_count+=1
         
     
    return inv_count
 
 
# find Position of blank from bottom
def findXPosition(puzzle):
    # start from bottom-right corner of matrix
    for i in range(N - 1,-1,-1):
        for j in range(N - 1,-1,-1):
            if (puzzle[i][j] == 0):
                return N - i
 
 
# This function returns true if given
# instance of N*N - 1 puzzle is solvable
def isSolvable(puzzle):
    # Count inversions in given puzzle
    invCount = getInvCount(puzzle)
 
    # If grid is odd, return true if inversion
    # count is even.
    if (N & 1):
        return ~(invCount & 1)
 
    else:    # grid is even
        pos = findXPosition(puzzle)
        if (pos & 1):
            return ~(invCount & 1)
        else:
            return invCount & 1